# Site settings
title: Fresh Audio
ryan_email: ryan@freshaudio.tv
ryan_number: +44 (0)7920 114 914
mandy_email: amanda@freshaudio.tv
mandy_number: +44 (0)7984 189 135
description: > # this means to ignore newlines until "baseurl:"
  Fresh Audio is an audio specific crewing company based in London and Manchester.
  We take the hassle out of booking good, friendly Location Sound Recordists to
  match your productions specific needs.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://freshaudio.tv" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
